apiVersion: v1
kind: Service
metadata:
  name: techmarket-orders-svc
  labels:
    app: techmarket-orders
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: techmarket-orders
    version: blue
