apiVersion: v1
kind: Service
metadata:
  name: techmarket-orders-preview
  labels:
    app: techmarket-orders
spec:
  type: NodePort
  selector:
    app: techmarket-orders
    version: green # Apunta al candidato a desplegar
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30092
