name: Deploy TechMarket Orders

on:
  push:
    branches: [ main ]

jobs:
  deploy-eks:
    uses: ciclocloud/shared-workflows/.github/workflows/eks-deployment.yaml@main
    with:
      aws_region: 'us-east-1'
      ecr_repository: 'techmarket-orders'
      cluster_name: 'techmarket-cluster'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
